### ISSUE TITLE
No working in lasted buildings of windows 10

### ISSUE THREAD

**Issue by sandhilt** [ie-web-notifications/ie-web-notifications.github.io#1]
No work in Internet Explorer 11 and Project Spartan of Windows 10 build 10074.

**Comment by ie-web-notifications** [comment]
Hi,
Thanks a lot for the report and sorry for the delay.
- I confirm that it indeed does not work in IE 11 on Win 10 build 10074, it seems some other plugins also don't work there. I will investigate it a little bit later.
- Regarding Project Spartan, it does not work and was not working with it because so far there is no information how to create extensions for it.

**Comment by ie-web-notifications** [comment]
Merely a small update of the investigation status (tried on IE11, win10-x64):
- neither 64-bit nor 32-bit version is still even loaded by IE (according to process monitor)
- signing of all executables does not help.

However the addon (BHO) is displayed as enabled in _Manage Add-ons_ dialog.

**Comment by ie-web-notifications** [comment]
It does not work because IE runs in _edge_ compatibility mode. So far I've managed only one way to change the compatibility mode to _IE11_ is via Developer Tools (F12) which is valid until Developer tools are opened, so not usable actually.
- By the way, it seems using `<meta http-equiv="x-ua-compatible" content="IE=10">` (if you are a web site maintainer) does not change the compatibility mode.  Note that **10** is used instead of **11** because
  
  > Starting with Internet Explorer 11, content values greater than "10" lead to edge mode, which is the highest version supported by the version of Internet Explorer used to view the webpage.
  > https://msdn.microsoft.com/en-us/library/jj676915(v=vs.85).aspx.
- Adding it to the compatibility list results in _IE7_ compatibility mode, which is also not usable.

In addition, on my machines Developer tools as well as changing of the compatibility note very often result in crashing of IE, be careful.

**Comment by ie-web-notifications** [comment]
It seems one can try to [Use Enterprise Mode to improve compatibility](https://technet.microsoft.com/en-us/library/mt270205.aspx) to set the compatibility mode for particular site.

**Comment by ie-web-notifications** [comment]
It turned out that I was testing on old Windows 10 (build 10158). After manual updating from https://www.microsoft.com/en-us/software-download/windows10 it does work on Windows 10 (build 10240) in IE11 (11.0.10240.16384).

**Comment by GregDThomas** [comment]
In case you're not aware, MS offer a download of a number of VMs with different IE versions for testing things just like this from http://dev.modern.ie/tools/vms/windows/

**Comment by ie-web-notifications** [comment]
Thanks a lot, I know it, but indeed I was not aware that they added Win10 image.

**Comment by ie-web-notifications** [comment]
Have they added win10 today https://blogs.windows.com/msedgedev/2015/08/17/windows-10-virtual-machines-now-available-on-microsoft-edge-dev/ ?

**Comment by GregDThomas** [comment]
I think so; it was that blog post that prompted me to add the above comment!
