### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by siddo420** [ie-web-notifications/ie-web-notifications.github.io#10]
is it similar to OS X notifications https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html? 

Or, it only works on IE?

Will it show notifications on desktop even if IE is not runnng?

**Comment by ie-web-notifications** [comment]
No, it's similar to https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/LocalNotifications/LocalNotifications.html and it does not allow to deliver notifications when a browser is not running.
However, current project is only for MS Internet Explorer. It is the addon for IE because [IE does not have](http://caniuse.com/#search=web%20notifications) such [Web Notifications API](http://www.w3.org/TR/notifications/).

Just for fun I have created several screenshots related to Web Notifications on Safari (9.0.1)
<img width="1051" alt="screen shot 2016-02-16 at 22 16 28" src="https://cloud.githubusercontent.com/assets/11330865/13092237/21ebd980-d4ff-11e5-8d44-80a54babba48.png">
<img width="1280" alt="screen shot 2016-02-16 at 22 19 41" src="https://cloud.githubusercontent.com/assets/11330865/13092234/21e7b292-d4ff-11e5-8d49-818de23c373b.png">
<img width="1267" alt="screen shot 2016-02-16 at 22 22 04" src="https://cloud.githubusercontent.com/assets/11330865/13092236/21eb7526-d4ff-11e5-9524-8ff7ff061b97.png">
<img width="1090" alt="screen shot 2016-02-16 at 22 24 12" src="https://cloud.githubusercontent.com/assets/11330865/13092235/21eb4fc4-d4ff-11e5-8add-791eeca261ac.png">
